CREATE TABLE RC_ANALISISLAB_UNIDADMEDIDA
(
RC_ANALISISLAB_UNIDADMEDIDA_id int NOT NULL IDENTITY(1,1),
RC_ANALISISLAB_id int FOREIGN KEY REFERENCES RC_ANALISISLAB(RC_ANALISISLAB_id),
RC_ANALISISLAB_UNIDADMEDIDA_nombre varchar(200)
PRIMARY KEY (RC_ANALISISLAB_id)
)

