CREATE TABLE AU_ROL_TAREA
(
AU_ROL_id int FOREIGN KEY REFERENCES AU_ROL(AU_ROL_id),
AU_TAREA_id int FOREIGN KEY REFERENCES AU_TAREA(AU_TAREA_id),
)

SELECT * FROM dbo.AU_ROL_TAREA art
SELECT * FROM AU_ROL
SELECT * FROM AU_TAREA

--ADMINISTRADOR
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,1)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,2)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,3)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,4)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,5)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,6)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,7)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,8)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,9)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,10)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,11)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,12)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,13)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,14)
INSERT INTO dbo.AU_ROL_TAREA VALUES (3,15)

--ROL TECNOLOGO
INSERT INTO dbo.AU_ROL_TAREA VALUES (4,2)
INSERT INTO dbo.AU_ROL_TAREA VALUES (4,8)
INSERT INTO dbo.AU_ROL_TAREA VALUES (4,9)
INSERT INTO dbo.AU_ROL_TAREA VALUES (4,13)
INSERT INTO dbo.AU_ROL_TAREA VALUES (4,14)
INSERT INTO dbo.AU_ROL_TAREA VALUES (4,15)



--MEDICO
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,1)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,2)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,3)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,4)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,5)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,6)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,7)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,8)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,9)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,10)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,11)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,12)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,13)
INSERT INTO dbo.AU_ROL_TAREA VALUES (1,14)

--TF

INSERT INTO dbo.AU_ROL_TAREA VALUES (5,16)
INSERT INTO dbo.AU_ROL_TAREA VALUES (5,17)