USE [RegistroClinico]
GO
SET IDENTITY_INSERT [dbo].[RC_ANALISIS_LAB] ON 

GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (1, N'Hemograma', N'36-50%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (2, N'Hematrocito', N'M: 12,1 - 15,1 g/dL <br> H: 13,8 - 17,2 g/dL  ', 2)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (3, N'Hemoglobina', N'86 - 95 ft', 3)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (4, N'VCM', N'28,2 - 32', 4)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (5, N'HCbG', N'31,9 - 36', 4)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (6, N'Leucocitos', N'3.500 - 10.000 mm³', 5)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (7, N'Eosinófilo', N'0 - 4%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (8, N'Basófilos', N'0 - 1%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (9, N'Mielocitos', N'0%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (10, N'Juveniles', N'3 - 5%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (11, N'Segmentados', N'55 - 65%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (12, N'Linfocitos', N'25 - 35%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (13, N'Monocitos', N'4 - 8%', 1)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (14, N'Recuento plaquetario', N'150.000 - 450.000 mm³', 5)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (15, N'VHS', N'M: <= 14mm <br> H: <=12mm', 6)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (16, N'TSH', N'0,4 - 4 mlU/L', 7)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (17, N'T3', N'100 - 200 ng/dl', 8)
GO
INSERT [dbo].[RC_ANALISIS_LAB] ([RC_ANALISIS_LAB_id], [RC_ANALISIS_LAB_nombre], [RC_ANALISIS_LAB_referencia], [RC_UNIDADMEDIDA_id]) VALUES (18, N'T4', N'4,5 y 12,5 ug/dl', 9)
GO
SET IDENTITY_INSERT [dbo].[RC_ANALISIS_LAB] OFF
GO
SET IDENTITY_INSERT [dbo].[RC_ESTADO] ON 

GO
INSERT [dbo].[RC_ESTADO] ([RC_ESTADO_id], [RC_ESTADO_nombre]) VALUES (1, N'Iniciado')
GO
INSERT [dbo].[RC_ESTADO] ([RC_ESTADO_id], [RC_ESTADO_nombre]) VALUES (2, N'Cerrado')
GO
SET IDENTITY_INSERT [dbo].[RC_ESTADO] OFF
GO
