CREATE TABLE RC_ANACLIARCHIVO(
	RC_ANACLIARCHIVO_id int identity(1,1) primary key,
	RC_ANALISISCLINICO_id int FOREIGN KEY REFERENCES RC_ANALISISCLINICO(RC_ANALISISCLINICO_id) NOT NULL,
	RC_ANACLIARCHIVO_archivo binary,
	RC_ANACLIARCHIVO_nombre nvarchar(100),
	RC_ANACLIARCHIVO_extension nvarchar(7),
	RC_ANACLIARCHIVO_tamano float,
	RC_ANACLIARCHIVO_ruta nvarchar(500)
)