CREATE TABLE RC_ARCHIVOPACIENTE
(
RC_ARCHIVOPACIENTE_id int NOT NULL IDENTITY(1,1),
RC_PACIENTE_rut int FOREIGN KEY REFERENCES RC_PACIENTE(RC_PACIENTE_rut),
RC_ARCHIVOPACIENTE_nombre varchar(50),
RC_ARCHIVOPACIENTE_extension varchar(50),
RC_ARCHIVOPACIENTE_tamano varchar(50),
RC_ARCHIVOPACIENTE_ruta varchar(200),
RC_ARCHIVOPACIENTE_vigencia bit,
PRIMARY KEY (RC_ARCHIVOPACIENTE_id)
)

