CREATE TABLE RC_APTITUDEXAMEN
(
RC_APTITUDEXAMEN_id smallint NOT NULL IDENTITY(1,1),
RC_APTITUDEXAMEN_nombre varchar(30)
PRIMARY KEY (RC_APTITUDEXAMEN_id)
)

INSERT INTO dbo.RC_APTITUDEXAMEN VALUES ('Apto')
INSERT INTO dbo.RC_APTITUDEXAMEN VALUES ('Con Restricciones')
INSERT INTO dbo.RC_APTITUDEXAMEN VALUES ('No Apto')