CREATE TABLE RC_DEPARTAMENTO
(
RC_DEPARTAMENTO_id smallint NOT NULL IDENTITY(1,1),
RC_DEPARTAMENTO_nombre varchar(30)
PRIMARY KEY (RC_DEPARTAMENTO_id)
)


SELECT * FROM dbo.RC_DEPARTAMENTO rs


INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('DE')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('JURÍDICA')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('GESTIÓN')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('DIFUS')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('COOPERACIÓN')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('AUDITORÍA')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('CALIDAD')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('DSNR')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('DPRA')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('DSA')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('P&S')
INSERT INTO dbo.RC_DEPARTAMENTO VALUES ('DID')
                    