CREATE TABLE RC_ESTADOCIVIL
(
RC_ESTADOCIVIL_id smallint NOT NULL IDENTITY(1,1),
RC_ESTADOCIVIL_nombre varchar(30)
PRIMARY KEY (RC_ESTADOCIVIL_id)
)

INSERT INTO dbo.RC_ESTADOCIVIL VALUES ('Soltero')
INSERT INTO dbo.RC_ESTADOCIVIL VALUES ('Casado')
INSERT INTO dbo.RC_ESTADOCIVIL VALUES ('Viudo')
INSERT INTO dbo.RC_ESTADOCIVIL VALUES ('Divorciado')
INSERT INTO dbo.RC_ESTADOCIVIL VALUES ('Separado')
INSERT INTO dbo.RC_ESTADOCIVIL VALUES ('Conviviente')



SELECT * FROM dbo.RC_ESTADOCIVIL rs
--DROP TABLE dbo.RC_ESTADOCIVIL