CREATE TABLE RC_ESTADOLICENCIAOPERACIONAL
(
RC_ESTADOLICENCIAOPERACIONAL_id smallint NOT NULL IDENTITY(1,1),
RC_ESTADOLICENCIAOPERACIONAL_nombre varchar(30),
RC_ESTADOLICENCIAOPERACIONAL_vigencia smallint,
PRIMARY KEY (RC_ESTADOLICENCIAOPERACIONAL_id)
)

INSERT INTO dbo.RC_ESTADOLICENCIAOPERACIONAL VALUES ('Creada',1)
INSERT INTO dbo.RC_ESTADOLICENCIAOPERACIONAL VALUES ('En curso',1)
INSERT INTO dbo.RC_ESTADOLICENCIAOPERACIONAL VALUES ('Cerrada',1)