CREATE TABLE RC_EXAMENFISICO
(
RC_EXAMENFISICO_id smallint NOT NULL IDENTITY(1,1),
RC_EXAMENFISICO_nombre varchar(100),
RC_EXAMENFISICO_vigencia smallint,
PRIMARY KEY (RC_EXAMENFISICO_id)
)
select * from RC_EXAMENFISICO
alter table rc_examenfisico alter column RC_EXAMENFISICO_nombre varchar(100)

INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Respiratorio',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Cardiovasculas',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Endocrino',1)

INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Tejidos, Tegumentos',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Hematopoyético y linfático',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Tejidos Neoplásticos',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Nervioso',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Enfermedades infecciosas, Parásitos o Venéreas',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Digestivo',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Sistema Óseo y Muscular',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Oido, Naríz y Garganta',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Exámenes de Laboratorio',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Audiometría',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Uremia',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Glicemia',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Colesterol',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Hemograma',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('V.H.S.',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('Electrocardiograma',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('',1)
INSERT INTO dbo.RC_EXAMENFISICO VALUES ('',1)