CREATE TABLE RC_ESTADOCITA
(
RC_ESTADOCITA_id smallint NOT NULL IDENTITY(1,1) ,
RC_ESTADOCITA_nombre varchar(20),
RC_ESTADOCITA_vigencia smallint,
PRIMARY KEY (RC_ESTADOCITA_id)
)

INSERT INTO dbo.RC_ESTADOCITA VALUES('Agendada',1)
INSERT INTO dbo.RC_ESTADOCITA VALUES('En Curso',1)
INSERT INTO dbo.RC_ESTADOCITA VALUES('Realizada',1)
INSERT INTO dbo.RC_ESTADOCITA VALUES('Cancelada',1)