CREATE TABLE RC_LICENCIAOPERACIONAL
(
RC_LICENCIAOPERACIONAL_id int NOT NULL IDENTITY(1,1),
RC_REGISTROCLINICO_id int FOREIGN KEY REFERENCES RC_REGISTROCLINICO(RC_REGISTROCLINICO_id),
RC_ESTADOLICENCIAOPERACIONAL_id smallint FOREIGN KEY REFERENCES RC_ESTADOLICENCIAOPERACIONAL(RC_ESTADOLICENCIAOPERACIONAL_id),
RC_LICENCIAOPERACIONAL_dias int, 
RC_LICENCIAOPERACIONAL_apreciacion varchar(200),
RC_LICENCIAOPERACIONAL_fecharegistro datetime,
RC_LICENCIAOPERACIONAL_fechainicio datetime,
RC_LICENCIAOPERACIONAL_fechafin datetime,
RC_LICENCIAOPERACIONAL_vigencia smallint,
PRIMARY KEY (RC_LICENCIAOPERACIONAL_id)
)


alter table RC_LICENCIAOPERACIONAL add RC_LICENCIAOPERACIONAL_vigencia smallint
select * from RC_REGISTROCLINICO
select * from RC_LICENCIAOPERACIONAL
select * from RC_LICENCIAOPERACIONAL_EXAMENFISICO

insert into RC_REGISTROCLINICO values (10371124,16626344)
set dateformat dmy
insert into RC_LICENCIAOPERACIONAL  
(RC_REGISTROCLINICO_id,	
RC_ESTADOLICENCIAOPERACIONAL_id,	
RC_LICENCIAOPERACIONAL_dias,	
RC_LICENCIAOPERACIONAL_apreciacion,
RC_LICENCIAOPERACIONAL_fecharegistro,	
RC_LICENCIAOPERACIONAL_fechainicio,	
RC_LICENCIAOPERACIONAL_fechafin)
values (
3,--RC_REGISTROCLINICO_id
1,--RC_ESTADOLICENCIAOPERACIONAL_id
10,--RC_LICENCIAOPERACIONAL_dias
'prueba2',--RC_LICENCIAOPERACIONAL_apreciacion
'10/10/2016',
'10/11/2016',
'10/12/2016')

insert into RC_LICENCIAOPERACIONAL_EXAMENFISICO values (2,1,1)
insert into RC_LICENCIAOPERACIONAL_EXAMENFISICO values (2,2,1)
insert into RC_LICENCIAOPERACIONAL_EXAMENFISICO values (2,3,1)