CREATE TABLE RC_NIVELEDUCACIONAL
(
RC_NIVELEDUCACIONAL_id smallint NOT NULL IDENTITY(1,1),
RC_NIVELEDUCACIONAL_nombre varchar(30)
PRIMARY KEY (RC_NIVELEDUCACIONAL_id)
)

INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Básico Incompleto')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Básico Completo')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Media Incompleto')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Media Completo')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Universitario Incompleto')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Universitario Completo')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Técnico Incompleto')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Técnico Completo')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Post-Grado Incompleto')
INSERT INTO dbo.RC_NIVELEDUCACIONAL VALUES ('Post-Grado Completo')


SELECT * FROM dbo.RC_NIVELEDUCACIONAL rs
DROP TABLE dbo.RC_NIVELEDUCACIONAL