CREATE TABLE RC_PREVISION
(
RC_PREVISION_id smallint NOT NULL IDENTITY(1,1),
RC_PREVISION_nombre varchar(30)
PRIMARY KEY (RC_PREVISION_id)
)

INSERT INTO dbo.RC_PREVISION VALUES ('Sin Previsión')
INSERT INTO dbo.RC_PREVISION VALUES ('Fonasa')
INSERT INTO dbo.RC_PREVISION VALUES ('Isapre')
INSERT INTO dbo.RC_PREVISION VALUES ('Otra')



SELECT * FROM dbo.RC_PREVISION rs
--DROP TABLE dbo.RC_PREVISION