CREATE TABLE RC_REGISTROCLINICO
(
RC_REGISTROCLINICO_id int NOT NULL IDENTITY(1,1),
RC_PACIENTE_rut int FOREIGN KEY REFERENCES RC_PACIENTE(RC_PACIENTE_rut),
RC_MEDICO_rut int FOREIGN KEY REFERENCES RC_MEDICO(RC_MEDICO_rut),
PRIMARY KEY (RC_REGISTROCLINICO_id)
)

insert into RC_REGISTROCLINICO values (18068473,16626344)
